import SkateLogo from "../skate.png";

const skateList = [
	{
		id: 1,
		name: "Toy Machine",
		category: "standard",
		isBestSale: true,
		width: 7.75,
		concave: "high",
		cover: SkateLogo,
		price: 75,
	},
	{
		id: 2,
		name: "Almost",
		category: "premium",
		isBestSale: false,
		width: 8.25,
		concave: "low",
		cover: SkateLogo,
		price: 100,
	},
	{
		id: 3,
		name: "Antihero",
		category: "pro model",
		isBestSale: true,
		width: 8,
		concave: "medium",
		cover: SkateLogo,
		price: 80,
	},
	{
		id: 4,
		name: "Blind",
		category: "standard",
		isBestSale: false,
		width: 8,
		concave: "high",
		cover: SkateLogo,
		price: 65,
	},
	{
		id: 5,
		name: "Palace",
		category: "premium",
		isBestSale: false,
		width: 8.25,
		concave: "low",
		cover: SkateLogo,
		price: 70,
	},
	{
		id: 6,
		name: "Baker",
		category: "pro model",
		isBestSale: true,
		width: 8,
		concave: "medium",
		cover: SkateLogo,
		price: 89,
	},
	{
		id: 7,
		name: "Chocolate",
		category: "standard",
		isBestSale: false,
		width: 7.75,
		concave: "high",
		cover: SkateLogo,
		price: 79,
	},
];

export default skateList;
